language: go
go:
  - 1.10.1
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - ./test.sh
sudo: false
notifications:
  email: false
